name: Check Terraform

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Terraform
        id: check_terraform
        run: terraform version
      - name: Setup Terraform
        if: failure() && steps.check_terraform.outcome == 'failure'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

