name: Check Terraform

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Check Terraform
        run: terraform version
        continue-on-error: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Check Terraform
        run: terraform version 

